import React from 'react'
import { Link } from 'react-router-dom'

class Work extends React.Component {


  render() {
    return (
      <div>
        <section className="container home">
          <h1 className="worktitle">Work</h1>
          <h3>View my Apps, Dashboards and Projects here</h3>

          <hr/>
          <br/>

          <div className="columns">
            <div className="column">
              <br/>
              <br/>
              <br/>
              <h2 className="subtitlework">Revenoo</h2>
              <br/>
              <h3>Business Bank Account Dashboard using React, Python and Django. This dashboard uses Authentication and Companies House API. Please make sure to register to view its full functionality, or view screenshots on my GitHub ReadMe file <a href="https://github.com/kubowania/Project-04">here.</a></h3>
              <br/>
              <a className="nav-subtitlelink" href="https://revenoo.herokuapp.com">Project</a>
            </div>
            <div className="column">
              <img width="600px" src="https://i.imgur.com/riSZvLg.png" title="Revenoo Dashboard"/>
              <img width="600px" src="https://i.imgur.com/R5m60rQ.png" title="Dashboard Homepage" />
            </div>
          </div>

          <br/>
          <br/>
          <br/>
          <div className="columns">
            <div className="column">
              <br/>
              <br/>
              <br/>
              <h2 className="subtitlework">BurgerRator</h2>
              <br/>
              <h3>An app that allows user to rate burgers as well as nominate their favourite. This dashboard uses Authentication and a geolocation API, aswell as Brewdogs open API. Please make sure to register to view its full functionality, or view screenshots on my GitHub ReadMe file <a href="https://github.com/kubowania/Project-03">here.</a></h3>
              <br/>
              <a className="nav-subtitlelink" href="https://burgerrator-app.herokuapp.com">Project</a>
            </div>
            <div className="column">
              <img width="600px" src="https://i.imgur.com/FoYsEv9.png" title="Burgerrator App" />
              <img width="600px" src="https://i.imgur.com/oJxA4zo.png" title="Create New Burger"/>
            </div>
          </div>

          <br/>
          <br/>
          <br/>
          <div className="columns">
            <div className="column">
              <br/>
              <br/>
              <br/>
              <h2 className="subtitlework">World News</h2>
              <br/>
              <h3>World News Website is a news aggregator which uses an API generated by The News API service. it was built as a 48hour Hackathon primarily using React. Read the full ReadMe <a href="https://github.com/kubowania/Project-2">here.</a></h3>
              <br/>
              <a className="nav-subtitlelink" href="https://aniakubow.com/Project-2/">Project</a>
            </div>
            <div className="column">
              <img width="600px" src="https://i.imgur.com/hv9BB1c.png?1" title="Main Headlines" />
              <img width="600px" src="https://i.imgur.com/CggN4aS.png?1" title="Show Page"/>
            </div>
          </div>

          <br/>
          <br/>
          <br/>
          <div className="columns">
            <div className="column">
              <br/>
              <br/>
              <br/>
              <h2 className="subtitlework">Tetris</h2>
              <br/>
              <h3>A vanilla JavaScript game using CSS and HTML5 for styling. Please view my GitHub Readme <a href="https://github.com/kubowania/Tetris">here.</a></h3>
              <br/>
              <a className="nav-subtitlelink" href="https://kubowania.github.io/Tetris/">Project</a>
            </div>
            <div className="column">
              <img width="600px" src="https://i.imgur.com/GwJFuuf.png?1" title="Tetris" />
              <img width="600px" src="https://i.imgur.com/JA1o0Rb.png?1" title="Rules of Tetris"/>
            </div>
          </div>

        </section>
      </div>
    )
  }
}
export default Work
